default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "djo" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "cicibu" } %>

development:
  <<: *default
  database: booking_development

test:
  <<: *default
  database: booking_test

production:
  <<: *default
  database: booking_production
  username: booking
  password: <%= ENV["BOOKING_DATABASE_PASSWORD"] %>